# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-01-18 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20190118_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='little_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
