# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-01-18 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_auto_20190118_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='little_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
